#
# Copyright (c) 2021-present Aaron Delasy
# Licensed under the MIT License
#

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - rm -rf node_modules package-lock.json
      - npm install --only=prod
      - mv node_modules build/
      - mv appspec.yml build/
      - mv start-app.sh build/

artifacts:
  files:
    - build/**/*

cache:
  paths:
    - /root/.npm/**/*
