#
# Copyright (c) 2018-present Aaron Delasy
# Licensed under the MIT License
#

version: 0.0

os: linux

files:
  - source: /
    destination: /app

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
